const productCategory = [
    { id: 1, label: "T-Shirts", value: "tshirts" },
    { id: 2, label: "Shirts", value: "shirts" },
    { id: 3, label: "Blouses", value: "blouses" },
    { id: 4, label: "Pants", value: "pants" },
    { id: 5, label: "Jeans", value: "jeans" },
    { id: 6, label: "Shorts", value: "shorts" },
    { id: 7, label: "Skirts", value: "skirts" },
    { id: 8, label: "Dresses", value: "dresses" },
    { id: 9, label: "Suits", value: "suits" },
    { id: 10, label: "Jackets", value: "jackets" },
    { id: 11, label: "Coats", value: "coats" },
    { id: 12, label: "Sweaters", value: "sweaters" },
    { id: 13, label: "Hoodies", value: "hoodies" },
    { id: 14, label: "Vests", value: "vests" },
    { id: 15, label: "Swimwear", value: "swimwear" },
    { id: 16, label: "Underwear", value: "underwear" },
    { id: 17, label: "Sleepwear", value: "sleepwear" },
    { id: 18, label: "Athletic Wear", value: "athletic-wear" },
]
export default productCategory